### ISSUE TITLE
Exception after closing with back-button

### ISSUE THREAD

**Issue by AdrianLxM** [monkey-r/ruffy#2]
After exiting the app with the back-button, exceptions happen as there is no UI-Thread:
```
05-24 22:08:13.053 10908-10962/? E/Tokens: error...
                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
                                               at org.monkey.d.ruffy.ruffy.MainFragment$13$1.menuFound(MainFragment.java:449)
                                               at org.monkey.d.ruffy.ruffy.driver.display.DisplayParser$1.run(DisplayParser.java:84)
                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                               at java.lang.Thread.run(Thread.java:761)


 and starting it again, the "connect" button is active but it cannot reconnect.
```

Subsequently (while exceptions still happen in the background):
 * Starting the app again will lead to a fresh screen with an active "connect" button and does not reconnect.

I guess, communication will be separated from the start activity and put into a Service (and for the loop driver no constant BT connection) anyways? -> low priority for testing the core functionality.

**Comment by SandraK82** [comment]
fixed
