### ISSUE TITLE
Deal with a dead service subscriber

### ISSUE THREAD

**Issue by jotomo** [monkey-r/ruffy#29]
When an app binds the ruffy service and crashes before unbinding from the ruffy service again, ruffy continues to invoke callback methods, each leading to a DeadObjectException. This requires a restart of ruffy to be resolved. If possible, ruffy should stop unbind from the subscriber (if possible from ruffy's end), to allow the other app to bind again after it has restarted.
```
07-23 13:48:40.328 28323 23675 W System.err: android.os.DeadObjectException
07-23 13:48:40.328 28323 23675 W System.err: 	at android.os.BinderProxy.transactNative(Native Method)
07-23 13:48:40.328 28323 23675 W System.err: 	at android.os.BinderProxy.transact(Binder.java:615)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.IRTHandler$Stub$Proxy.log(IRTHandler.java:148)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Ruffy.log(Ruffy.java:355)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Ruffy$5.log(Ruffy.java:296)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Application.processAppResponse(Application.java:330)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Ruffy$6.handleResponse(Ruffy.java:396)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Packet.handleRX(Packet.java:158)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Packet.handleRawData(Packet.java:94)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.Ruffy$2.handleRawData(Ruffy.java:180)
07-23 13:48:40.329 28323 23675 W System.err: 	at org.monkey.d.ruffy.ruffy.driver.BTConnection$1.run(BTConnection.java:189)
```

**Comment by SandraK82** [comment]
Fixed in head
