### ISSUE TITLE
Ruffy crashes on pairing

### ISSUE THREAD

**Issue by AdrianLxM** [monkey-r/ruffy#30]
```
07-25 17:33:24.852 3734-3734/org.monkey.d.ruffy.ruffy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: org.monkey.d.ruffy.ruffy, PID: 3734
                                                                        java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.device.action.ACL_CONNECTED flg=0x4000010 (has extras) } in org.monkey.d.ruffy.ruffy.driver.ConnectReceiver@1afb17e
                                                                            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
                                                                            at org.monkey.d.ruffy.ruffy.SetupFragment.appendLog(SetupFragment.java:131)
                                                                            at org.monkey.d.ruffy.ruffy.SetupFragment.access$000(SetupFragment.java:37)
                                                                            at org.monkey.d.ruffy.ruffy.SetupFragment$1.log(SetupFragment.java:88)
                                                                            at org.monkey.d.ruffy.ruffy.driver.ConnectReceiver.onReceive(ConnectReceiver.java:36)
                                                                            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
                                                                            at android.os.Handler.handleCallback(Handler.java:751) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by SandraK82** [comment]
Seen but yet unable to reproduce for testing.

**Comment by SandraK82** [comment]
Maybe fixed with latest guards

**Comment by Mondelman** [comment]
I did some testing after compiling module. It crashed after moving a bit through menus. Unfortunately, the phone I used, a Motorola G3, has no SIM (it's broken), and now on trip, so I am not carrying it with me.
I will try to upload it once back home.
My Combo is not my actual pump today, as I have an Animas Vibe. If I can try anything for you, please feel free to comment.
