### ISSUE TITLE
Ruffy crash after unbonding

### ISSUE THREAD

**Issue by AdrianLxM** [monkey-r/ruffy#33]
```
07-30 15:01:58.870 19735-19735/org.monkey.d.ruffy.ruffy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.monkey.d.ruffy.ruffy, PID: 19735
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineTop(int)' on a null object reference
                                                                              at android.os.Parcel.readException(Parcel.java:1690)
                                                                              at android.os.Parcel.readException(Parcel.java:1637)
                                                                              at org.monkey.d.ruffy.ruffy.driver.IRuffyService$Stub$Proxy.doRTConnect(IRuffyService.java:168)
                                                                              at org.monkey.d.ruffy.ruffy.MainFragment$1.onServiceConnected(MainFragment.java:90)
                                                                              at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                                              at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

After unbonding and AAPS still trying to access RUFFY. (might be coincidence)

**Comment by AdrianLxM** [comment]
Even after a restart of the phone and no access from AndroidAPS, Ruffy crashes with this exception at startup.

**Comment by boysim** [comment]
Same issue here on a clean install in android emulator.

**Comment by AdrianLxM** [comment]
Even after a full uninstall of Ruffy and reinstall this issue continues to exist.

**Comment by SandraK82** [comment]
fixed
