### ISSUE TITLE
Crash due to NPE: bt disconnect when exiting with back button

### ISSUE THREAD

**Issue by AdrianLxM** [monkey-r/ruffy#34]
Ruffy is not connected.
Exiting with back button.
Commit-Hash: 1238a8b

```
07-30 18:01:33.146 10603-10603/org.monkey.d.ruffy.ruffy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.monkey.d.ruffy.ruffy, PID: 10603
                                                                          java.lang.RuntimeException: Unable to destroy activity {org.monkey.d.ruffy.ruffy/org.monkey.d.ruffy.ruffy.Start}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.BTConnection.disconnect()' on a null object reference
                                                                              at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4240)
                                                                              at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
                                                                              at android.app.ActivityThread.-wrap6(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.BTConnection.disconnect()' on a null object reference
                                                                              at android.os.Parcel.readException(Parcel.java:1690)
                                                                              at android.os.Parcel.readException(Parcel.java:1637)
                                                                              at org.monkey.d.ruffy.ruffy.driver.IRuffyService$Stub$Proxy.doRTDisconnect(IRuffyService.java:185)
                                                                              at org.monkey.d.ruffy.ruffy.MainFragment.onDestroy(MainFragment.java:124)
                                                                              at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2951)
                                                                              at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
                                                                              at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
                                                                              at android.app.Activity.performDestroy(Activity.java:6886)
                                                                              at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
                                                                              at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)
                                                                              at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258) 
                                                                              at android.app.ActivityThread.-wrap6(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6186) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by SandraK82** [comment]
fixed in 02ac513745a3979a811e212783c95664711fa2bb
