### ISSUE TITLE
Ruffy closing on startup

### ISSUE THREAD

**Issue by Illiteratus** [monkey-r/ruffy#37]
08-13 19:18:27.641 24180-24180/org.monkey.d.ruffy.ruffy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.monkey.d.ruffy.ruffy, PID: 24180
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineTop(int)' on a null object reference
                                                                              at android.os.Parcel.readException(Parcel.java:1690)
                                                                              at android.os.Parcel.readException(Parcel.java:1637)
                                                                              at org.monkey.d.ruffy.ruffy.driver.IRuffyService$Stub$Proxy.doRTConnect(IRuffyService.java:168)
                                                                              at org.monkey.d.ruffy.ruffy.MainFragment$1.onServiceConnected(MainFragment.java:90)
                                                                              at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                                              at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

Install ok. On app start welcome screen appears for a fraction of a second and the app closes each time with "Ruffy wurde beendet".....

(Git:stable ; build:release)

**Comment by SandraK82** [comment]
should be fixed in latest develop

**Comment by boysim** [comment]
Yes it is! Thnx

**Comment by SandraK82** [comment]
fixed in develop bdbeaa30babbb724de8fea5484a6463b9164d015

**Comment by Illiteratus** [comment]
Thanks a lot...
