### ISSUE TITLE
NPE on void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)

### ISSUE THREAD

**Issue by gregorybel** [monkey-r/ruffy#46]
Version: c8049d5-combo-scripter-v2-2018-01-31

```
02-11 08:59:51.650 E/AndroidRuntime(4457): FATAL EXCEPTION: Thread-4707
02-11 08:59:51.650 E/AndroidRuntime(4457): Process: org.monkey.d.ruffy.ruffy.driver.Ruffy, PID: 4457
02-11 08:59:51.650 E/AndroidRuntime(4457): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
02-11 08:59:51.650 E/AndroidRuntime(4457): 	at android.os.Parcel.readException(Parcel.java:1671)
02-11 08:59:51.650 E/AndroidRuntime(4457): 	at android.os.Parcel.readException(Parcel.java:1618)
02-11 08:59:51.650 E/AndroidRuntime(4457): 	at org.monkey.d.ruffy.ruffy.driver.IRTHandler$Stub$Proxy.rtStarted(IRTHandler.java:206)
02-11 08:59:51.650 E/AndroidRuntime(4457): 	at org.monkey.d.ruffy.ruffy.driver.Ruffy$3.run(Ruffy.java:278)
02-11 11:21:26.463 E/AndroidRuntime(18149): FATAL EXCEPTION: Thread-945
02-11 11:21:26.463 E/AndroidRuntime(18149): Process: org.monkey.d.ruffy.ruffy.driver.Ruffy, PID: 18149
02-11 11:21:26.463 E/AndroidRuntime(18149): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
02-11 11:21:26.463 E/AndroidRuntime(18149): 	at android.os.Parcel.readException(Parcel.java:1671)
02-11 11:21:26.463 E/AndroidRuntime(18149): 	at android.os.Parcel.readException(Parcel.java:1618)
02-11 11:21:26.463 E/AndroidRuntime(18149): 	at org.monkey.d.ruffy.ruffy.driver.IRTHandler$Stub$Proxy.rtStarted(IRTHandler.java:206)
02-11 11:21:26.463 E/AndroidRuntime(18149): 	at org.monkey.d.ruffy.ruffy.driver.Ruffy$3.run(Ruffy.java:278)
```

**Comment by jotomo** [comment]
@gregorybel I think this bug is only present in my branch.
When did this occur?

**Comment by gregorybel** [comment]
@jotomo yes your branch. Dont know exactly, but during this time aaps restarted. Do you want aaps logs and compare with timestamps?

**Comment by jotomo** [comment]
Did you manually open ruffy (before or while AAPS ran)? I don't see this happening without ruffy's UI being initialized, or initializing when AAPS crashed/restarted.

**Comment by gregorybel** [comment]
might be so if this is the cause then we can close this issue as it's not a use case.
