### ISSUE TITLE
Crash when running in emulator

### ISSUE THREAD

**Issue by zsmith3** [monkey-r/ruffy#47]
`
03-01 16:49:26.828 2760-2760/org.monkey.d.ruffy.ruffy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.NullPointerException
                                                                            at android.os.Parcel.readException(Parcel.java:1431)
                                                                            at android.os.Parcel.readException(Parcel.java:1379)
                                                                            at org.monkey.d.ruffy.ruffy.driver.IRuffyService$Stub$Proxy.doRTConnect(IRuffyService.java:168)
                                                                            at org.monkey.d.ruffy.ruffy.MainFragment$1.onServiceConnected(MainFragment.java:90)
                                                                            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1097)
                                                                            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1114)
                                                                            at android.os.Handler.handleCallback(Handler.java:615)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                            at dalvik.system.NativeStart.main(Native Method)
`

I get this error when attempting to run the app in an Android emulator. I've tried with versions 4.1 (API 16) and 8.1 (API 27) and get the exact same error.

**Comment by jotomo** [comment]
The emulator doesn't emulate a Bluetooth adapter, so there isn't much of a point in running ruffy in an emulator.
