### ISSUE TITLE
Bolus cancelled dialog

### ISSUE THREAD

**Issue by AdrianLxM** [monkey-r/ruffy#6]
Happens e.g. when you enter stop mode but have an extended bolus running.
![screenshot_20170525-143933](https://cloud.githubusercontent.com/assets/9692866/26450569/641dfd6c-4158-11e7-9af1-e104cfdf683f.png)

Issue 1: Gets detected as **display found: STOP**.
Issue 2: Nullpointer exception while parsing.

log:
```
05-25 14:39:03.293 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.293 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:39:03.293 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 559 reliable: false
05-25 14:39:03.293 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: UNKNOWN
05-25 14:39:03.297 7789-8072/org.monkey.d.ruffy.ruffy V/Tokens: 27 found
05-25 14:39:03.298 7789-8072/org.monkey.d.ruffy.ruffy W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.display.Menu.setAttribute(org.monkey.d.ruffy.ruffy.driver.display.MenuAttribute, java.lang.Object)' on a null object reference
05-25 14:39:03.298 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at org.monkey.d.ruffy.ruffy.driver.display.DisplayParser$1.run(DisplayParser.java:84)
05-25 14:39:03.298 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.lang.Thread.run(Thread.java:761)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy E/Tokens: error...
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.display.Menu.setAttribute(org.monkey.d.ruffy.ruffy.driver.display.MenuAttribute, java.lang.Object)' on a null object reference
                                                                    at org.monkey.d.ruffy.ruffy.driver.display.DisplayParser$1.run(DisplayParser.java:84)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:761)
05-25 14:39:03.299 7789-8072/org.monkey.d.ruffy.ruffy V/Tokens: 0.017 secs needed for frame
05-25 14:39:03.564 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 127: CC 10 03 69 00 01 32 DF 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 81 15 48 4F 47 00 00 00 00 00 00 00 1C 22 41 41 7F 00 41 49 49 49 7F 00 40 40 40 40 7F 00 40 40 40 40 7F 00 41 49 49 49 7F 00 22 41 41 41 3E 00 7F 10 08 04 7F 00 7C 0A 09 0A 7C 00 22 41 41 41 3E 00 00 00 00 00 00 00 31 49 49 49 46 00 3F 40 40 40 3F 00 40 40 40 40 7F 00 3E 41 41 41 3E 00 36 49 49 49 7F 50 E9 1C 
05-25 14:39:03.564 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.565 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 6: 35 12 8A 2B 69 CC 
05-25 14:39:03.565 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.566 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:39:03.566 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:39:03.571 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:39:03.600 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 127: CC 10 03 69 00 01 33 DF 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 82 15 48 4F 48 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 61 41 49 
05-25 14:39:03.600 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.601 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 6: 49 F8 EE F4 6E CC 
05-25 14:39:03.601 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.601 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:39:03.602 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:39:03.604 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:39:03.632 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 127: CC 10 03 69 00 01 34 DF 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 83 15 48 4F B7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 B1 DE 72 
05-25 14:39:03.632 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:39:03.652 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 139: 71 AD 8D E9 D6 CC CC 10 03 69 00 01 35 DF 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 84 15 48 4F B8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 82 92 92 92 FE 00 86 8A 92 A2 C2 00 7C 82 82 82 7C 00 7C 82 82 82 7C 00 FE 20 10 08 FE 00 62 92 92 92 8C 00 00 00 00 00 00 00 7C 82 82 82 7C 00 02 02 FE 02 02 00 00 00 00 00 00 00 06 0C 18 30 18 60 BA 5C 5C AE 94 0B 2C CC 
05-25 14:39:03.652 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
```

**Comment by AdrianLxM** [comment]
log for the following screen when pressing "ok":
![screenshot_20170525-144658](https://cloud.githubusercontent.com/assets/9692866/26450763/46af5efa-4159-11e7-8a27-7993106eb7ad.png)
(TO CONFIRM instead of TO SNOOZE as text)
```
05-25 14:40:01.771 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:40:01.772 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:40:01.772 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:40:01.775 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:40:01.775 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:40:01.776 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:40:01.778 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:40:01.799 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 133: CC 10 03 69 00 01 38 E2 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 87 18 48 09 B7 00 00 00 00 00 07 0F 1F 3C 7F 7C 7D 7C 7F 7F 7C 7F 3F 1C 0D 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1F 3F 60 40 40 60 3F 1F 00 00 00 00 00 00 00 1F 3F 70 38 1F 1F 38 70 3F 1F 00 00 00 00 00 00 00 00 00 00 00 00 00 60 78 6E 63 60 60 60 6B 6B 60 60 60 63 6E 78 20 00 00 00 00 00 80 39 B8 B7 61 DF 87 2E CC 
05-25 14:40:01.799 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:40:01.800 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:40:01.800 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:40:01.803 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:40:01.829 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 127: CC 10 03 69 00 01 39 E2 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 88 18 48 09 B8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FE 04 18 04 FE 00 8C 52 32 12 FE 00 00 82 FE 82 00 00 02 12 12 12 FE 00 FE 20 10 08 FE 00 7C 82 82 82 7C 00 44 82 82 82 7C 00 00 00 00 00 00 00 7C 82 82 82 7C 00 02 02 FE 02 02 00 00 00 00 00 00 00 06 0C 18 30 18 16 50 6A 
05-25 14:40:01.829 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:40:01.830 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 6: 7B BB 18 F7 41 CC 
05-25 14:40:01.830 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:40:01.830 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: processing app response
05-25 14:40:01.830 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: Service ID: 48 Comm ID: 555 reliable: false
05-25 14:40:01.833 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: appProcess: null
05-25 14:40:01.833 7789-8072/org.monkey.d.ruffy.ruffy V/Tokens: ----------------------------------
05-25 14:40:01.844 7789-8072/org.monkey.d.ruffy.ruffy V/Tokens: 28 found
05-25 14:40:01.845 7789-8072/org.monkey.d.ruffy.ruffy W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.display.Menu.setAttribute(org.monkey.d.ruffy.ruffy.driver.display.MenuAttribute, java.lang.Object)' on a null object reference
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at org.monkey.d.ruffy.ruffy.driver.display.DisplayParser$1.run(DisplayParser.java:84)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy W/System.err:     at java.lang.Thread.run(Thread.java:761)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy E/Tokens: error...
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void org.monkey.d.ruffy.ruffy.driver.display.Menu.setAttribute(org.monkey.d.ruffy.ruffy.driver.display.MenuAttribute, java.lang.Object)' on a null object reference
                                                                    at org.monkey.d.ruffy.ruffy.driver.display.DisplayParser$1.run(DisplayParser.java:84)
                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:761)
05-25 14:40:01.846 7789-8072/org.monkey.d.ruffy.ruffy V/Tokens: 0.013 secs needed for frame
05-25 14:40:02.155 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 127: CC 10 03 69 00 01 3A E2 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 89 18 48 0A 47 00 00 00 00 00 00 00 1C 22 41 41 7F 00 41 49 49 49 7F 00 40 40 40 40 7F 00 40 40 40 40 7F 00 41 49 49 49 7F 00 22 41 41 41 3E 00 7F 10 08 04 7F 00 7C 0A 09 0A 7C 00 22 41 41 41 3E 00 00 00 00 00 00 00 31 49 49 49 46 00 3F 40 40 40 3F 00 40 40 40 40 7F 00 3E 41 41 41 3E 00 36 49 49 49 7F 08 8A E2 
05-25 14:40:02.155 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
05-25 14:40:02.172 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: read 139: 8B 13 EB C0 45 CC CC 10 03 69 00 01 3B E2 01 00 00 00 00 00 00 00 00 00 00 10 48 55 05 8A 18 48 0A 48 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 B7 45 08 1A FB 79 28 AF CC 
05-25 14:40:02.172 7789-7949/org.monkey.d.ruffy.ruffy V/RUFFY_LOG: got data from pump
```
